"""
Safe Python Executor for Tool Calling

Provides a sandboxed environment for executing Python code
generated by the model during latent reasoning.
"""

import sys
import io
import contextlib
from typing import Tuple
import ast


class PythonExecutor:
    """
    Safe Python code executor with output capture.
    
    Usage:
        executor = PythonExecutor(timeout=10)
        success, output = executor.execute("print(12345 * 678)")
        # output: "8369910"
    """
    
    def __init__(self, timeout: int = 30, max_output_length: int = 10000):
        """
        Args:
            timeout: Maximum execution time in seconds (not enforced in basic version)
            max_output_length: Maximum length of output to return
        """
        self.timeout = timeout
        self.max_output_length = max_output_length
    
    def _validate_code(self, code: str) -> Tuple[bool, str]:
        """
        Validate Python code for safety.
        
        Returns:
            (is_valid, error_message)
        """
        # Try to parse the code
        try:
            ast.parse(code)
        except SyntaxError as e:
            return False, f"Syntax error: {e}"
        
        return True, ""
    
    def execute(self, code: str) -> Tuple[bool, str]:
        """
        Execute Python code and return the result.
        
        Args:
            code: Python code to execute
            
        Returns:
            (success, output_or_error)
        """
        # Validate code
        is_valid, error = self._validate_code(code)
        if not is_valid:
            return False, error
        
        # Capture stdout
        stdout_capture = io.StringIO()
        
        # Import allowed modules
        import math
        import random
        import statistics
        import itertools
        
        # Try to import optional modules
        try:
            import numpy as np
        except ImportError:
            np = None
        
        try:
            import sympy
        except ImportError:
            sympy = None
        
        # Build safe globals with explicit imports
        safe_globals = {
            '__builtins__': {
                'print': print,
                'range': range,
                'len': len,
                'int': int,
                'float': float,
                'str': str,
                'list': list,
                'dict': dict,
                'tuple': tuple,
                'set': set,
                'sum': sum,
                'max': max,
                'min': min,
                'abs': abs,
                'round': round,
                'sorted': sorted,
                'enumerate': enumerate,
                'zip': zip,
                'map': map,
                'filter': filter,
                'any': any,
                'all': all,
                'isinstance': isinstance,
                'type': type,
                'bool': bool,
                'True': True,
                'False': False,
                'None': None,
                # Add __import__ for module imports
                '__import__': __import__,
                # Add complex number support
                'complex': complex,
            },
            # Pre-imported modules
            'math': math,
            'random': random,
            'statistics': statistics,
            'itertools': itertools,
            'sqrt': math.sqrt,
            'comb': getattr(math, 'comb', None),
            'gcd': getattr(math, 'gcd', None),
        }
        
        # Add optional modules
        if np is not None:
            safe_globals['np'] = np
            safe_globals['numpy'] = np
        if sympy is not None:
            safe_globals['sympy'] = sympy
        
        # Execute with captured output
        # IMPORTANT: Use same dict for both globals and locals to ensure
        # that function definitions are accessible to other functions.
        # When exec() uses separate dicts, functions are stored in locals
        # but other functions can't find them because they look in globals.
        try:
            with contextlib.redirect_stdout(stdout_capture):
                exec(code, safe_globals, safe_globals)
            
            output = stdout_capture.getvalue().strip()
            
            # Truncate if too long
            if len(output) > self.max_output_length:
                output = output[:self.max_output_length] + "...[truncated]"
            
            return True, output
            
        except Exception as e:
            error_msg = f"Execution error: {type(e).__name__}: {str(e)}"
            return False, error_msg
    
    def execute_with_fallback(self, code: str, fallback_value: str = "ERROR") -> str:
        """
        Execute code and return output, or fallback value on error.
        
        Args:
            code: Python code to execute
            fallback_value: Value to return on error
            
        Returns:
            Output string or fallback value
        """
        success, output = self.execute(code)
        if success:
            return output
        else:
            print(f"[ToolExecutor] Error: {output}")
            return fallback_value


def test_executor():
    """Test the executor with sample code."""
    executor = PythonExecutor()
    
    # Test cases
    test_cases = [
        ("print(12345 * 678)", "8369910"),
        ("print(sum(range(10)))", "45"),
        ("from math import sqrt; print(round(sqrt(2), 4))", "1.4142"),
        ("import random; random.seed(42); print(random.randint(1, 100))", "82"),
        ("from math import comb; print(comb(6, 2) * comb(8, 2))", "420"),
    ]
    
    print("Testing PythonExecutor:")
    for code, expected in test_cases:
        success, output = executor.execute(code)
        status = "✓" if success and output.strip() == expected.strip() else "✗"
        print(f"  {status} {code[:50]}... -> {output}")
    
    print("\nDone.")


if __name__ == "__main__":
    test_executor()
